# Generated by Django 4.1.3 on 2023-01-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_comentaristas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comentaristas',
        ),
    ]
