# Generated by Django 4.1.3 on 2023-01-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_autor_post_user_remove_post_comentaristas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fechc']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='contc',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fechc',
        ),
    ]
