# Generated by Django 4.1.3 on 2023-01-20 16:10

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearComentario',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.edit.CreateView, 'blog.post'),
        ),
    ]
