# Generated by Django 4.1.3 on 2023-01-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usario',
            new_name='usuario',
        ),
    ]
