# Generated by Django 4.1.3 on 2023-01-08 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_rename_usario_perfil_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
