# Generated by Django 4.1.3 on 2023-01-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_user_profile_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
