# Generated by Django 4.1.3 on 2023-01-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars\\avatarpordefecto.png', upload_to='avatars'),
        ),
    ]
